import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/components/layout/header";
import Providers from "./providers";
import Loader from "../components/ui/Loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col justify-between bg-black">
        <Providers>
          <Header />
          <div className="mt-21">{children}</div>
          <Loader/>
        </Providers>
      </body>
    </html>
  );
}
